#!/bin/sh

# Symlink this into .git/hooks/prepare-commit-msg to start with a reasonable
# commit message when modifying a single day's code.

# Redirect output to stderr.
exec 1>&2

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"
SHA1="$3"

# Bail out if there's already a commit source:
# https://mincong.io/2019/07/23/prepare-commit-message-using-git-hook/
[ -z "$COMMIT_SOURCE" ] || exit 0

# Save the existing hint and clear the file.
HINT=$(cat "$COMMIT_MSG_FILE")
echo -n >"$COMMIT_MSG_FILE"
TITLE=

# Skip tests unless we're modifying something in the lib package.
if ! git diff --cached --name-only | grep -q '^lib/'; then
  TITLE='[ci skip]'
fi

# Prefix the title with the day if we're modifying a single file from a day dir.
DAYFILES="$(git diff --cached --name-only | grep -E '^[0-9]{4}/[0-9]{2}/main\.go$')"
if [ "$(echo "$DAYFILES" | sed '/^\s*$/d' | wc -l)" -eq 1 ]; then
  TITLE="$(echo "$DAYFILES" | cut -c 1-7):  ${TITLE}"
fi

echo "$TITLE" >"$COMMIT_MSG_FILE"
echo "$HINT" >>"$COMMIT_MSG_FILE"
