#!/bin/sh

# Symlink this into .git/hooks/commit-msg to check that
# commit messages don't reference the wrong day (a mistake
# that I keep making).

# Redirect output to stderr.
exec 1>&2

MSG="$1"
DAYFILES="$(git diff --cached --name-only | grep -E '^[0-9]{4}/[0-9]{2}/main\.go$')"

# Bail out if we're not committing a single file from a day dir.
[ "$(echo "$DAYFILES" | sed '/^\s*$/d' | wc -l)" -eq 1 ] || exit 0

# Construct the desired prefix, e.g. '2020/01: '.
PREFIX="$(echo "$DAYFILES" | cut -c 1-7): "

if ! grep -qE "^${PREFIX}" "$MSG"; then
    cat "$MSG"
    echo "Commit message should start with '${PREFIX}'"
    exit 1
fi
